<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION ARTIFICIAL   (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date | custom)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION STATUS    	( UNKNOWN | SKIPPED | UNSUPPORTED | FAILURE | PARTIAL | APPLIED | APPLIED_OTHER )	#IMPLIED>
  <!-- STATUS defaults to APPLIED if BYTES specified and TYPE is non-zero  -->
  <!-- STATUS defaults to APPLIED_OTHER if BYTES specified and TYPE is zero  -->
  <!-- STATUS defaults to UNKNOWN if BYTES are not specified  -->
  <!ATTLIST RELOCATION TYPE     	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION VALUE    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION BYTES    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION SYMBOL_NAME	CDATA	#IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY COMMENT  CDATA  #REQUIRED>

]>
<PROGRAM NAME="EarthBound_Zero_Mother_1-u_202305.nes" EXE_PATH="/C:/Users/ghumphrey/Documents/Projects/Ghidra Projects/ROMs/earth-bound-zero-mother-1-u_202305/EarthBound_Zero_Mother_1-u_202305.nes" EXE_FORMAT="NES ROM" IMAGE_BASE="0000">
    <INFO_SOURCE USER="ghumphrey" TOOL="Ghidra 11.3" TIMESTAMP="Tue Apr 08 05:18:25 EDT 2025" />
    <PROCESSOR NAME="6502" LANGUAGE_PROVIDER="6502:LE:16:default:default" ENDIAN="little" />
    <DATATYPES>
        <STRUCTURE NAME="AllyData" NAMESPACE="/" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Experience" SIZE="0x1">
                <REGULAR_CMT>Divide by 0x100 to get exp multiplier</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Unknown" SIZE="0x1">
                <REGULAR_CMT>Probably unused</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="PP" SIZE="0x1">
                <REGULAR_CMT>Controls which level character gets PP, 0 means no PSI</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Fight" SIZE="0x1" />
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Speed" SIZE="0x1" />
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Wisdom" SIZE="0x1" />
            <MEMBER OFFSET="0x6" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Strength" SIZE="0x1" />
            <MEMBER OFFSET="0x7" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Force" SIZE="0x1" />
        </STRUCTURE>
        <TYPE_DEF NAME="byte" NAMESPACE="/rpcndr.h" DATATYPE="uchar" DATATYPE_NAMESPACE="/" />
        <STRUCTURE NAME="EncounterGroup" NAMESPACE="/" SIZE="0x10">
            <MEMBER OFFSET="0x0" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x3" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x6" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x7" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x8" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x9" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xa" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xb" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xc" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xd" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xe" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xf" DATATYPE="byte" DATATYPE_NAMESPACE="/" SIZE="0x1" />
        </STRUCTURE>
        <STRUCTURE NAME="EnemyData" NAMESPACE="/" SIZE="0x20">
            <MEMBER OFFSET="0x0" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Unknown" SIZE="0x1" />
            <MEMBER OFFSET="0x1" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Initial status" SIZE="0x1" />
            <MEMBER OFFSET="0x2" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Flags" SIZE="0x1">
                <REGULAR_CMT>[0]: Vuln. to spray. [1]: Res. PK Beam. [2]: Imm. to conf./sleep. [3]: Unk. [4]: Res. PK Thun. [5]: Res. PK Frz. [6]: Res. PK Fire. [7]: Imm. to status</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="HP1" SIZE="0x1" />
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="HP2/Sub-palette/Graph.Tile.Arr." SIZE="0x1">
                <REGULAR_CMT>[0:1]: HP2. [2:3]: Sub-palette. [4:7]: Graphic tile arrangement</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="PP1" SIZE="0x1" />
            <MEMBER OFFSET="0x6" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="PP2/Extra graphics" SIZE="0x1">
                <REGULAR_CMT>[0:1]: PP2. [2:7]: Extra graphics</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x7" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Offense1" SIZE="0x1" />
            <MEMBER OFFSET="0x8" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Offense2/FinalAction/Altitude" SIZE="0x1">
                <REGULAR_CMT>[0:1]: Offense2. [2:4]: Final action (1=explode, 2=flames). [5:7]: Altitude</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x9" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Defense1" SIZE="0x1" />
            <MEMBER OFFSET="0xa" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Defense2/DefeatMsg/Unk" SIZE="0x1">
                <REGULAR_CMT>[0:1]: Defense2. [2:4]: Defeat msg. [5:7]: Unk</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xb" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Fight" SIZE="0x1" />
            <MEMBER OFFSET="0xc" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Speed" SIZE="0x1" />
            <MEMBER OFFSET="0xd" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Wisdom" SIZE="0x1" />
            <MEMBER OFFSET="0xe" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Strength" SIZE="0x1" />
            <MEMBER OFFSET="0xf" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Force" SIZE="0x1" />
            <MEMBER OFFSET="0x10" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Attacks1" SIZE="0x1" />
            <MEMBER OFFSET="0x11" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Attacks2" SIZE="0x1" />
            <MEMBER OFFSET="0x12" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Attacks3" SIZE="0x1" />
            <MEMBER OFFSET="0x13" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Attacks4" SIZE="0x1" />
            <MEMBER OFFSET="0x14" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Attacks5" SIZE="0x1" />
            <MEMBER OFFSET="0x15" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Attacks6" SIZE="0x1" />
            <MEMBER OFFSET="0x16" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Attacks7" SIZE="0x1" />
            <MEMBER OFFSET="0x17" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Attacks8" SIZE="0x1" />
            <MEMBER OFFSET="0x18" DATATYPE="pointer16" DATATYPE_NAMESPACE="/" NAME="Name ptr" SIZE="0x2">
                <REGULAR_CMT>Points to bank 0</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1a" DATATYPE="short" DATATYPE_NAMESPACE="/" NAME="Experience" SIZE="0x2" />
            <MEMBER OFFSET="0x1c" DATATYPE="short" DATATYPE_NAMESPACE="/" NAME="Money" SIZE="0x2" />
            <MEMBER OFFSET="0x1e" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Item dropped" SIZE="0x1" />
            <MEMBER OFFSET="0x1f" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Graphics Tileset" SIZE="0x1" />
        </STRUCTURE>
        <STRUCTURE NAME="EnemyGroup" NAMESPACE="/" SIZE="0xa">
            <MEMBER OFFSET="0x0" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Enemy1 Type" SIZE="0x1">
                <REGULAR_CMT>FF for none, offset from start of EnemyData</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Enemy1 Letter/CallIn" SIZE="0x1">
                <REGULAR_CMT>[0:6]: Enemy letter (0=none, 1=A, 2=B...). [7]: Only appear when called</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Enemy2 Type" SIZE="0x1">
                <REGULAR_CMT>FF for none, offset from start of EnemyData</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Enemy2 Letter/CallIn" SIZE="0x1">
                <REGULAR_CMT>[0:6]: Enemy letter (0=none, 1=A, 2=B...). [7]: Only appear when called</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Enemy3 Type" SIZE="0x1">
                <REGULAR_CMT>FF for none, offset from start of EnemyData</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Enemy3 Letter/CallIn" SIZE="0x1">
                <REGULAR_CMT>[0:6]: Enemy letter (0=none, 1=A, 2=B...). [7]: Only appear when called</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x6" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Enemy4 Type" SIZE="0x1">
                <REGULAR_CMT>FF for none, offset from start of EnemyData</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x7" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Enemy4 Letter/CallIn" SIZE="0x1">
                <REGULAR_CMT>[0:6]: Enemy letter (0=none, 1=A, 2=B...). [7]: Only appear when called</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x8" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Position/Special" SIZE="0x1">
                <REGULAR_CMT>[0:4]: Positioning. [5:7]: Special encounter (1=BB Boss, 2=R7037, 3=R7038, 4=R7038XX, 5=Giegue)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x9" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Palette/Music" SIZE="0x1">
                <REGULAR_CMT>[0:3]: Palette. [4:7]: Music</REGULAR_CMT>
            </MEMBER>
        </STRUCTURE>
        <STRUCTURE NAME="ItemData" NAMESPACE="/" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="pointer16" DATATYPE_NAMESPACE="/" NAME="Name ptr" SIZE="0x2">
                <REGULAR_CMT>Pointer within bank</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Flags" SIZE="0x1">
                <REGULAR_CMT>0-5: Who can use. 6: Edible. 7: Can&apos;t be dropped.</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Equipment" SIZE="0x1">
                <REGULAR_CMT>0-5: Attack (weapon), defense (coin/ring), or resistance (pendant). 6-7: Type (0=weapon, 1=coin, 2=ring, 3=pendant)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Action (non-battle)" SIZE="0x1" />
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Action (battle)" SIZE="0x1" />
            <MEMBER OFFSET="0x6" DATATYPE="short" DATATYPE_NAMESPACE="/" NAME="Price" SIZE="0x2" />
        </STRUCTURE>
        <STRUCTURE NAME="PSIData" NAMESPACE="/" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="pointer16" DATATYPE_NAMESPACE="/" NAME="Name ptr" SIZE="0x2">
                <REGULAR_CMT>Pointer within bank</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Ninten&apos;s level" SIZE="0x1">
                <REGULAR_CMT>00 or FF means can&apos;t learn.  Add 1 to level.</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Ana&apos;s level" SIZE="0x1" />
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="World action ID" SIZE="0x1" />
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Battle action ID" SIZE="0x1" />
            <MEMBER OFFSET="0x6" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Unused" SIZE="0x1" />
            <MEMBER OFFSET="0x7" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="PP cost" SIZE="0x1" />
        </STRUCTURE>
        <STRUCTURE NAME="TeleportTarget" NAMESPACE="/" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="pointer16" DATATYPE_NAMESPACE="/" NAME="Name ptr" SIZE="0x2">
                <REGULAR_CMT>Pointer within bank</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Music" SIZE="0x1">
                <REGULAR_CMT>See music table for IDs</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="X Coord" SIZE="0x1">
                <REGULAR_CMT>Dist from left of map</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Entrance info" SIZE="0x1">
                <REGULAR_CMT>[0-3]: Stop minitile: 0-3: Upper right. 4-7: Upper middle. 8-B: Lower middle. C-F: Bottom right.  [4-7]: Run in from: 0: U. 1: UR. 2: R. 3: DR. 4: D. 5: DL. 6: L. 7: LU. 8: Shuffle</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Y Coord" SIZE="0x1">
                <REGULAR_CMT>Dist from top of map</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x6" DATATYPE="short" DATATYPE_NAMESPACE="/" NAME="Unused" SIZE="0x2" />
        </STRUCTURE>
        <STRUCTURE NAME="TrainDest" NAMESPACE="/" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="pointer16" DATATYPE_NAMESPACE="/" NAME="Name ptr" SIZE="0x2">
                <REGULAR_CMT>Pointer within bank</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Music+XStart1" SIZE="0x1">
                <REGULAR_CMT>[0:5] Music. [6-7] Train start X pt 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="XStart2" SIZE="0x1">
                <REGULAR_CMT>Train start X pt 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="Direction+YStart1" SIZE="0x1">
                <REGULAR_CMT>[0:5] Start direction. [6-7] Train start Y pt 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="YStart2" SIZE="0x1">
                <REGULAR_CMT>Train start Y pt 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x6" DATATYPE="short" DATATYPE_NAMESPACE="/" NAME="Price" SIZE="0x2" />
        </STRUCTURE>
    </DATATYPES>
    <MEMORY_MAP>
        <MEMORY_SECTION NAME="RAM" START_ADDR="0000" LENGTH="0x800" PERMISSIONS="rwx" />
        <MEMORY_SECTION NAME="RAM_MIRROR_1" START_ADDR="0800" LENGTH="0x800" PERMISSIONS="rwx">
            <BYTE_MAPPED SOURCE_ADDRESS="0000" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="RAM_MIRROR_2" START_ADDR="1000" LENGTH="0x800" PERMISSIONS="rwx">
            <BYTE_MAPPED SOURCE_ADDRESS="0000" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="RAM_MIRROR_3" START_ADDR="1800" LENGTH="0x800" PERMISSIONS="rwx">
            <BYTE_MAPPED SOURCE_ADDRESS="0000" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="PPU" START_ADDR="2000" LENGTH="0x8" PERMISSIONS="rw" VOLATILE="y" />
        <MEMORY_SECTION NAME="PPU_MIRROR_1" START_ADDR="2008" LENGTH="0x8" PERMISSIONS="rw" VOLATILE="y">
            <BYTE_MAPPED SOURCE_ADDRESS="2000" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="PPU_MIRROR_2" START_ADDR="2010" LENGTH="0x10" PERMISSIONS="rw" VOLATILE="y">
            <BYTE_MAPPED SOURCE_ADDRESS="2000" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="PPU_MIRROR_3" START_ADDR="2020" LENGTH="0x20" PERMISSIONS="rw" VOLATILE="y">
            <BYTE_MAPPED SOURCE_ADDRESS="2000" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="PPU_MIRROR_4" START_ADDR="2040" LENGTH="0x40" PERMISSIONS="rw" VOLATILE="y">
            <BYTE_MAPPED SOURCE_ADDRESS="2000" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="PPU_MIRROR_5" START_ADDR="2080" LENGTH="0x80" PERMISSIONS="rw" VOLATILE="y">
            <BYTE_MAPPED SOURCE_ADDRESS="2000" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="PPU_MIRROR_6" START_ADDR="2100" LENGTH="0x100" PERMISSIONS="rw" VOLATILE="y">